aug:
  image_aug: true
  masked_language_model: true
backbone: vgg19_bn
cnn:
  hidden: 256
  ks:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
  pretrained: true
  ss:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  - - 2
    - 1
  - - 1
    - 1
dataloader:
  num_workers: 3
  pin_memory: true
dataset:
  data_root: /mnt/disk1/mbbank/OCR/DATA/data_quangnd/new_train
  image_height: 32
  image_max_width: 512
  image_min_width: 32
  name: data_team
  train_annotation: /mnt/disk1/mbbank/OCR/DATA/team/train.txt
  valid_annotation: /mnt/disk1/mbbank/OCR/DATA/team/val.txt
device: cuda:0
optimizer:
  max_lr: 5.0e-04
  pct_start: 0.1
predictor:
  beamsearch: false
pretrain: https://vocr.vn/data/vietocr/vgg_transformer.pth
quiet: false
seq_modeling: transformer
trainer:
  batch_size: 128
  checkpoint:
  export: /mnt/disk1/mbbank/OCR/CODE/VietOcr/weight/vietocr_V3.pth
  iters: 300000
  log: ./train.log
  metrics: 150
  print_every: 200
  valid_every: 400
transformer:
  d_model: 256
  dim_feedforward: 2048
  max_seq_length: 1024
  nhead: 8
  num_decoder_layers: 6
  num_encoder_layers: 6
  pos_dropout: 0.1
  trans_dropout: 0.1
vocab: aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
  –üāö
weights: https://vocr.vn/data/vietocr/vgg_transformer.pth
